version: "3.2"

services:
  keycloak:
    image: "quay.io/keycloak/keycloak:22.0"
    env_file: env.d/keycloak
    command: start-dev
    ports:
      - "8890:8080"
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - keycloak_dev_network
             
  postgres_keycloak:
    image: postgres:15.4
    env_file: env.d/keycloak
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      - keycloak_dev_network

volumes:
  pgdata_keycloak:
networks:
  keycloak_dev_network:
    driver: bridge
            
