spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8890/realms/Test
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8091

jwt:
  auth:
    converter:
      resource-id: test-rest-api
      principle-attribute: preffered_username


